# Playbook to perform initial config of blue1-fw
- name: vyos network config
  hosts: vyos
  tasks:
    - name: load vyos config from template
      become: yes
      template:
        src: /home/jared-adm/Documents/SYS-480/ansible/files/vyos/config.boot.j2
        dest: /config/config.boot
        mode: 0775
        owner: root
        group: vyattacfg
    - name: bounce and end
      become: yes
      shell: nohup bash -c "/usr/bin/sleep 5 && /usr/sbin/shutdown -r now" &